### ISSUE TITLE
Something not right with spawn amounts with latest version

### ISSUE THREAD

**Issue by Zygus42** [MinecraftModDevelopmentMods/OreSpawn#4] opened 2016-09-13 05:05 UTC
orespawn-2.0.0.4-1.10.2, BaseMetals_1.10.2-2.4.0.11, forge-1.10.2-12.18.1.2076

I've been trying to adjust the spawn rate for base metal metals, and something is just not right.  As an example, Mercury settings:
      {
        "block": "basemetals:mercury_ore",
        "size": 3,
        "variation": 2,
        "frequency": 2,
        "min_height": 0,
        "max_height": 32
      },
And I'm still getting lots of it, and in lots of around 10 in a clump.  Other metals seem to be adjusting better, but still don't quite seem to match the config settings.

Use the config file I've set up and see the results for yourself.
[basemetals.zip](https://github.com/MinecraftModDevelopment/OreSpawn/files/468928/basemetals.zip)

By the way - World Stripper is a great new testing tool for this kind of thing.

**Comment by JCMais** [comment] 2016-10-16 05:21
I'm getting too many diamonds on my latest world, same version than @Zygus42. They are spawning at the same rate than Redstone. Using the default settings.

**Comment by dshadowwolf** [comment] 2017-06-23 15:40
OreSpawn 3 is due to be released in the next week or two - if both of you could give it a try (it's 1.11.2 and above) and let us know if the issue is fixed or if we need to rework the default algorithm it'd be very helpful.

**Comment by dshadowwolf** [comment] 2017-07-04 10:26
@Zygus42 @JCMais Can either of you test OreSpawn 3 and report on whether or not this issue is continuing ?

**Comment by JCMais** [comment] 2017-07-04 11:47
@dshadowwolf Sorry, I'm currently not able to test it, since I've stopped playing minecraft for quite a while.

**Comment by dshadowwolf** [comment] 2017-08-24 19:08
Assuming lack of response from @Zygus42 and the changes to the code-base in v3 have resolved this for v3 - closing.

**Closed by dshadowwolf** 2017-08-24 19:08 UTC
Labels: bug, v2
